#' Load All CEDAR R Functions
#'
#' Loads all R source files in dependency order:
#'   1. lists/    — static constants and domain lookups
#'   2. trunk/    — pure infrastructure (filter, utils, cache, logging, data I/O)
#'   3. branches/ — reusable cedar domain computations (enrollment, grades, cohort)
#'   4. cones/    — single-question analyses; call trunk/branches, never other cones
#'   5. features/ — app-facing orchestration and payload builders
#'   6. modules/  — Shiny UI/server pairs
#'
#' @param cedar_base_dir Character. The base directory of the CEDAR project.
#' @export
load_funcs <- function(cedar_base_dir, modules = TRUE) {
  message("[load-funcs.R] Welcome to load_funcs! Loading R files...")
  message("[load-funcs.R] cedar_base_dir: ", cedar_base_dir)

  source_file <- function(relative_path) {
    full_path <- file.path(cedar_base_dir, "R", relative_path)
    if (!file.exists(full_path)) {
      stop("[load-funcs.R] File not found: ", full_path)
    }
    source(full_path)
  }

  # 1. Lists (static data, no dependencies)
  message("[load-funcs.R] Loading lists...")
  source_file("lists/excluded_courses.R")
  source_file("lists/gen_ed_courses.R")
  source_file("lists/grades.R")
  source_file("lists/subj_dept_map.R")      # college → dept → subject hierarchy
  source_file("lists/program_code_maps.R") # manual override maps for Banner program code parsing
  # program_map.qs is generated by scripts/update-data.sh (with the 'as' report).
  # Assigned to .GlobalEnv so catalog_lookups.R (sourced in the global env below) can find it.
  # Required — catalog_lookups.R derives major_college_to_dept and major_to_dept from it.
  .pm_path <- file.path(cedar_base_dir, "data", "program_map.qs")
  if (!file.exists(.pm_path))
    stop("[load-funcs.R] program_map.qs not found at: ", .pm_path,
         "\n  Run scripts/update-data.sh with the 'as' report to generate it.")
  program_map <- qs2::qs_read(.pm_path)
  assign("program_map", program_map, envir = .GlobalEnv)
  rm(.pm_path)
  source_file("lists/catalog_lookups.R")   # derives lookup vectors from program_map + subj_dept_map
  source_file("lists/mappings.R")          # text/name maps not derivable from catalogs
  source_file("lists/status_codes.R")
  source_file("lists/campuses.R")           # campus codes, default scope, campus guards

  # 2. Trunk (pure infrastructure — no cedar domain knowledge)
  message("[load-funcs.R] Loading trunk...")
  # utils.R first: it defines the CEDAR_* palette/tint constants that other
  # trunk files (datatable_helpers.R's COLOR_SCHEMES) evaluate at source time.
  # It is self-contained — its only load-time call is to its own
  # make_term_sequence() — so it is safe at the front.
  source_file("trunk/utils.R")
  source_file("trunk/cache.R")
  source_file("trunk/changelog.R")
  source_file("trunk/data.R")
  source_file("trunk/datatable_helpers.R")
  source_file("trunk/filter.R")
  source_file("trunk/logging.R")
  source_file("trunk/url-state.R")          # shareable-URL round-trip registry + copy/restore helpers
  source_file("trunk/reporting.R")

  # 3. Branches (reusable cedar domain computations — called by multiple cones/features)
  message("[load-funcs.R] Loading branches...")
  source_file("branches/enrl.R")
  source_file("branches/credit-hours.R")
  source_file("branches/data-edges.R")            # where the loaded data starts/stops; see the right-edge policy in AGENTS.md
  source_file("branches/credit-timeline.R")  # per-term credit position; see the field reliability contract in AGENTS.md
  source_file("branches/gpa-timeline.R")     # per-term cumulative GPA; shares credit_timeline_validity(), so must load after it
  source_file("branches/degrees.R")
  source_file("branches/course-attempts.R")
  source_file("branches/course-flows.R")
  source_file("branches/demographics.R")       # student demographic summaries (used by course-demographics + waitlist cones)
  source_file("branches/headcount.R")
  source_file("branches/population.R")
  source_file("branches/comparison.R")         # treatment/control group builder for observational analyses
  source_file("branches/pathways.R")           # pure helpers for Pathways module analysis scoping
  source_file("lists/population-presets.R")    # defines PATHWAYS_MAJOR_GROUP_PRESETS for populationSelectorUI()

  # 4. Cones (single-question analyses — call trunk/branches, never other cones)
  message("[load-funcs.R] Loading cones...")
  source_file("cones/bottleneck.R")
  source_file("cones/course-neighbors.R")
  source_file("cones/major-changes.R")
  source_file("cones/stopout.R")
  source_file("cones/course-outcomes.R")
  source_file("cones/pathway.R")
  source_file("cones/population-trend.R")
  source_file("cones/course-demographics.R")
  source_file("cones/seatfinder.R")
  source_file("cones/cancellations.R")
  source_file("cones/sfr.R")
  source_file("cones/waitlist.R")
  source_file("cones/course-impact.R")         # retention, sequence, and instructor effect analyses
  source_file("cones/course-retention.R")      # institution-level retention by course and over time
  source_file("cones/gen-ed-conversion.R")     # gen ed flow tables + course-major associations
  source_file("cones/gen-ed-grads.R")          # gen ed uptake among a dept's readable graduates

  # 5. Features (app-facing orchestration — call multiple branches/cones)
  message("[load-funcs.R] Loading features...")
  source_file("features/course-report.R")
  source_file("features/dept-dashboard.R")
  source_file("features/dept-trends.R")
  source_file("features/gen-ed.R")
  source_file("features/regstats.R")

  # 6. Shiny modules (depend on branches + cones)
  if (modules) {
    message("[load-funcs.R] Loading Shiny modules...")
    source_file("modules/ui-helpers.R")    # shared UI helpers (info_panel, empty_state)
    source_file("modules/headcount.R")
    source_file("modules/seatfinder.R")
    source_file("modules/cancellations.R")
    source_file("modules/waitlist.R")
    source_file("modules/regstats.R")
    source_file("modules/admin.R")
    source_file("modules/gen-ed.R")
    source_file("modules/dept-trends.R")
    source_file("modules/pathways.R")
    source_file("modules/retention.R")
  } else {
    message("[load-funcs.R] Skipping Shiny modules (modules = FALSE).")
  }

  message("[load-funcs.R] All functions loaded successfully!")
  invisible(NULL)
}
