# mappings.R
#
# Hand-curated text/name lookup maps that cannot be derived from unit_catalog or program_catalog.
#
# Contents:
#   major_to_program_map    — Program name text → program code.
#                             Used for graduate student data where MyReports provides only a
#                             text name (e.g., "Biology") rather than a Banner program code.
#   hr_org_desc_to_dept_map — HR "Home Organization Desc" text → dept_code.
#                             Used in parse-HRreport.R and dept-report.R.
#   program_code_to_name    — program_code → human-readable display name.
#                             Supplements data-derived names (~24% coverage) for cedar_lookups.
#
# SUPERSEDED — do NOT re-add these; they are now derived from unit_catalog.R and
# program_catalog.R by catalog_lookups.R (loaded before this file):
#   subj_to_dept_map      → catalog_lookups.R (from unit_catalog)
#   college_name_to_code  → catalog_lookups.R (from unit_catalog)
#   dept_code_to_name     → catalog_lookups.R (from unit_catalog dept_name)
#   dept_display_names    → catalog_lookups.R (from unit_catalog dept_name)
#   prgm_to_dept_map      → catalog_lookups.R (from program_catalog)
#   old_code_to_new_code  → unit_catalog subject_code → dept_code mappings


# Maps program name text to program codes.
# Used for grad student data and any path where only a text name is available.
# NOTE: values are program codes (e.g., "CRIM"), not dept codes. The program_catalog
# or prgm_to_dept_map (derived from catalog_lookups.R) maps program → dept.
major_to_program_map <- c(
  "American Studies"="AMST",
  "Africana Studies"="AFST",
  "African American Studies"="AFST",
  "Anthropology"="ANTH",
  "American Sign Language"="ASL",
  "Arabic" = "ARBC",
  "Asian Studies"="EAS",
  "Astrophyics"="ASTR",
  "Biology"="BIOL",
  "Biology/Biological Sciences"="BIOL",
  "Biochemistry"="BIOC",
  "Chemistry"="CHEM",
  "Chicana and Chicano Studies"="CCS",
  "Chicana Chicano Studies"="CCS",
  "Chicana/o Studies"="CCS",
  "Chinese"="CHIN",
  "Classical Studies"="CLST",
  "Communication Journalism"="CJ",
  "Communication & Journalism"="CJ",
  "Communication"="COMM",
  "Comp Lit & Cultural Stds"="CLCS",
  "Comp Lit & Cultural Studies"="CLCS",
  "Comparative Literature"="CLCS",
  "Criminology"="CRIM",
  "Creative Writing"="CRWR",
  "Earth & Planetary Sciences"="EPS",
  "East Asian Studies"="EAS",
  "Economics"="ECON",
  "English"="ENGL",
  "English Studies"="ENGS",
  "English-Philosophy"="ENGP",
  "Environmental Science"="ENSC",
  "French"="FREN",
  "French Studies"="FRNS",
  "Foreign Languages Literatures"="LCL",
  "Forensic Anthropology"="ANTH",
  "Forensic Science"="ANTH",
  "Geography"="GEOG",
  "German"="GRMN",
  "German Studies"="GRMS",
  "Greek"="GREK",
  "Health,Medicine & Human Values"="HMHV",
  "History"="HIST",
  "International Studies"="ISI",
  "Italian"="ITAL",
  "Japanese"="JAPN",
  "Journal & Mass Comm"="JOUR",
  "Journalism"="JOUR",
  "Journalism & Mass Comm"="JOUR",
  "Languages Cultures & Literatures"="LCL",
  "Languages"="LANG",
  "Latin"="LATN",
  "Latin American Studies"="LTAM",
  "Linguistics"="LING",
  "Mass Communication"="COMM",
  "Mathematics"="MATH",
  "Mathematics Statistics"="MATH",
  "Museum Studies"="MSST",
  "Native American Studies"="NATV",
  "Navajo Language & Linguistics" = "NVJO",
  "Philosophy"="PHIL",
  "Physics"="PHYS",
  "Physics & Astrophysics"="PHYS",
  "Physics Astronomy"="PHYS",
  "Astrophysics"="ASTR",
  "Political Science"="POLS",
  "Political Science Gen Admin"="POLS",
  "Portuguese"="PORT",
  "School of Public Admin"="PADM",
  "School of Public Administration"="PADM",
  "Public Administration"="PADM",
  "Psychology"="PSYC",
  "Religious Studies Prgm"="RELG",
  "Religious Studies"="RELG",
  "Russian"="RUSS",
  "Russian Studies"="RUSS",
  "Signed Language Interpreting"="SIGN",
  "Signed Language Interpret"="SIGN",
  "Sociology"="SOCI",
  "Spanish" = "SPAN",
  "Spanish Portuguese" = "SPAN",
  "Spanish & Portuguese" = "SPAN",
  "Speech & Hearing Sciences" = "SHS",
  "Speech and Hearing Sciences" = "SHS",
  "Speech-Language Pathology" = "SHS",
  "Statistics" = "STAT",
  "Sustainability Studies" = "SUST",
  "Sustainability Studies Program" = "SUST",
  "Technical & Professional Comm" = "TCOM",
  "Women Studies"="WGSS",
  "Womens Studies"="WGSS",
  "Wmn, Gndr, Sexlty Studies"="WGSS",
  "Women, Gndr, Sexuality Studies"="WGSS")


# Maps HR "Home Organization Desc" field to dept codes.
# Used in parse-HRreport.R and dept-report.R.
hr_org_desc_to_dept_map <- c(
  "American Studies"="AMST",
  "AS American Studies"="AMST",
  "Africana Studies"="AFST",
  "African American Studies"="AFST",
  "African American Studies Gen Admin"="AFST",
  "AS Anthropology"="ANTH",
  "Anthropology"="ANTH",
  "AS Biology"="BIOL",
  "AS Biology General Administrative"="BIOL",
  "AS BA/MD Program"="HMHV",
  "Biology"="BIOL",
  "Biology/Biological Sciences"="BIOL",
  "Biochemistry"="BIOC",
  "Chemistry"="CHEM",
  "AS Chemistry"="CHEM",
  "Chicana / Chicano Studies"="CCS",
  "Chicana and Chicano Studies"="CCS",
  "AS Chicana and Chicano Studies"="CCS",
  "Communication Journalism"="CJ",
  "Communication & Journalism"="CJ",
  "Earth & Planetary Sciences Dept"="EPS",
  "Earth and Planetary Sciences Dept"="EPS",
  "Earth and Planetary Sciences E PS"="EPS",
  "Earth & Planetary Sciences"="EPS",
  "AS Economics"="ECON",
  "Economics"="ECON",
  "English"="ENGL",
  "AS English"="ENGL",
  "English Studies"="ENGL",
  "English General Administrative"="ENGL",
  "Environmental Science"="EPS",
  "Geography"="GES",
  "Geography and Environmental Studies"="GES",
  "Health,Medicine & Human Values"="HMHV",
  "History"="HIST",
  "AS History"="HIST",
  "International Studies"="ISI",
  "International Studies Institute ISI"="ISI",
  "Mass Communication"="CJ",
  "Foreign Language Lit Gen Admin"="LCL",
  "Languages Cultures & Literatures"="LCL",
  "Languages Cultures & Lit Gen Admin"="LCL",
  "Foreign Languages Literatures"="LCL",
  "Latin American Studies"="LTAM",
  "Linguistics"="LING",
  "AS Linguistics"="LING",
  "Mathematics Statistics"="MATH",
  "AS Mathematics Statistics"="MATH",
  "Museum Studies"="MSST",
  "Native American Studies"="NATV",
  "AS Native American Studies"="NATV",
  "Philosophy"="PHIL",
  "AS Philosophy"="PHIL",
  "Physics"="PHYS",
  "Physics Astronomy"="PHYS",
  "AS Physics Astronomy"="PHYS",
  "CAS/CQuIC"="PHYS",
  "Physics Astronomy Gen Admin"="PHYS",
  "Political Science"="POLS",
  "AS Political Science"="POLS",
  "Political Science Gen Admin"="POLS",
  "School of Public Administration"="PADM",
  "Psychology"="PSYC",
  "AS Psychology"="PSYC",
  "Religious Studies Prgm"="RELG",
  "Religious Studies"="RELG",
  "Sociology"="SOCI",
  "AS Sociology"="SOCI",
  "Spanish Portuguese" = "SPAN",
  "Spanish & Portuguese" = "SPAN",
  "AS Spanish Portuguese" = "SPAN",
  "Speech and Hearing Sciences" = "SHS",
  "Speech & Hearing Sciences" = "SHS",
  "AS Speech and Hearing Sciences" = "SHS",
  "Speech Hearing Sciences Gen Admin" = "SHS",
  "Sustainability Studies Program" = "SUST",
  "Women Gender and Sexuality Studies" = "WGSS",
  "AS Women Gender and Sexuality Studies" = "WGSS",
  "Womens Studies"="WGSS")


# Maps program codes to human-readable display names.
# Supplements data-derived names; used in credit-hours.R and dept-dashboard.R.
# Covers pre-majors, old codes, and codes where the data-derived name is absent or poor.
program_code_to_name <- c(
  # Arts & Sciences programs
  "AFST"="Africana Studies",
  "AMST"="American Studies",
  "ANTH"="Anthropology",
  "ARTH"="Art History",
  "ARTS"="Studio Art",
  "ASTR"="Astronomy",
  "BIOC"="Biochemistry",
  "BIOL"="Biology",
  "CCS"="Chicana/o Studies",
  "CHEM"="Chemistry",
  "CHIN"="Chinese",
  "CJ"="Communication & Journalism",
  "CLCS"="Comparative Lit",
  "CLST"="Classical Studies",
  "COMM"="Communication",
  "CRIM"="Criminology",
  "CRWR"="Creative Writing",
  "EAS"="East Asian Studies",
  "ECON"="Economics",
  "ENGL"="English",
  "ENGS"="English Studies",
  "EPS"="Earth & Planetary Sci",
  "EVSC"="Environmental Science",
  "FREN"="French",
  "GES"="Geography",
  "GERM"="German",
  "GSCI"="General Science",
  "GNST"="General Studies",
  "HIST"="History",
  "INTS"="International Studies",
  "JAPN"="Japanese",
  "LANG"="Languages",
  "LING"="Linguistics",
  "LTAM"="Latin American Studies",
  "MATH"="Mathematics",
  "NATV"="Native American Studies",
  "PHIL"="Philosophy",
  "PHYS"="Physics",
  "POLS"="Political Science",
  "PORT"="Portuguese",
  "PSY"="Psychology",
  "PSYC"="Psychology",
  "RELG"="Religious Studies",
  "RUSS"="Russian",
  "SIGN"="Signed Language",
  "SOCI"="Sociology",
  "SPAN"="Spanish",
  "SUST"="Sustainability Studies",
  "WGSS"="Women & Gender Studies",

  # Pre-majors / Freshman intent (F prefix)
  "FHIS"="Pre-History",
  "FANTH"="Pre-Anthropology",
  "FBIO"="Pre-Biology",
  "FCHM"="Pre-Chemistry",
  "FPSY"="Pre-Psychology",
  "FECO"="Pre-Economics",
  "FPOL"="Pre-Political Science",
  "FMAT"="Pre-Mathematics",
  "FPHY"="Pre-Physics",
  "FBAD"="Pre-Business",
  "FAST"="Pre-Art Studio",
  "FCRI"="Pre-Criminology",
  "FELE"="Pre-Elementary Ed",
  "FSEC"="Pre-Secondary Ed",
  "FTHR"="Pre-Theatre",
  "FDMA"="Pre-Digital Media",
  "FFDA"="Pre-Film/Digital Arts",
  "FCS"="Pre-Computer Science",
  "FME"="Pre-Mechanical Eng",
  "FEE"="Pre-Electrical Eng",
  "FCE"="Pre-Civil Eng",
  "FCH"="Pre-Chemical Eng",
  "FES"="Pre-Env Science",
  "FBIC"="Pre-Biochemistry",

  # Business & Management
  "BADM"="Business Admin",
  "XBAD"="Business Admin (Extended)",
  "ACCT"="Accounting",
  "MGMT"="Management",
  "MKTG"="Marketing",
  "FIN"="Finance",

  # Engineering
  "ME"="Mechanical Eng",
  "EE"="Electrical Eng",
  "CE"="Civil Eng",
  "CHE"="Chemical Eng",
  "CS"="Computer Science",
  "CPE"="Computer Eng",
  "NE"="Nuclear Eng",
  "ES"="Engineering Science",

  # Health Sciences
  "NURS"="Nursing",
  "PHRD"="Pharmacy",
  "DEHY"="Dental Hygiene",
  "RADS"="Radiologic Sciences",
  "MEDL"="Medical Lab Science",
  "NUAP"="Nursing (Advanced)",
  "SHS"="Speech & Hearing",
  "OCTH"="Occupational Therapy",
  "PTHE"="Physical Therapy",
  "NUTR"="Nutrition",

  # Education
  "ELED"="Elementary Education",
  "SPED"="Special Education",
  "EDUC"="Education",
  "TESL"="TESOL",

  # Fine Arts
  "MUS"="Music",
  "THEA"="Theatre",
  "DANC"="Dance",
  "FILM"="Film Studies",
  "ARCT"="Architecture",
  "ARDT"="Art & Design",

  # Law
  "LAW"="Law",

  # Other programs
  "LART"="Liberal Arts",
  "LIBA"="Liberal Arts",
  "SCI"="Science",
  "COM"="Community",
  "EMS"="Emergency Med Services",

  # Non-program statuses
  "NOND"="Non-Degree",
  "UNDC"="Undeclared",
  "UNDG"="Undeclared Grad",
  "EXCH"="Exchange Student",
  "VSIT"="Visiting Student"
)
