# Test setup - runs before all tests
#
# Two types of fixtures are available:
#
# 1. KNOWN FIXTURES (known_sections, known_students, etc.)
#    Hand-crafted data with predetermined expected values.
#    Use these for behavioral tests that assert specific counts/values.
#    Source: fixtures/known_test_data.R (version-controlled, never auto-generated)
#
# 2. SCHEMA FIXTURES (test_sections, test_students, etc.)
#    Sampled from real CEDAR data for schema validation tests.
#    Use these to verify data transformations produce correct columns.
#    Source: fixtures/cedar_*_test.qs (generated by create-test-fixtures.R)

# Load necessary libraries
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(qs)
})

# -----------------------------------------------------------------------------
# KNOWN FIXTURES - hand-crafted with predetermined expected values
# -----------------------------------------------------------------------------
source("fixtures/known_test_data.R")

# Export to global environment for tests
known_sections <<- known_sections
known_students <<- known_students
known_programs <<- known_programs
known_degrees <<- known_degrees
known_faculty <<- known_faculty
known_courses <<- known_sections  # alias

# -----------------------------------------------------------------------------
# SCHEMA FIXTURES - sampled from real data for schema validation
# -----------------------------------------------------------------------------
# These may not exist if create-test-fixtures.R hasn't been run
schema_fixtures_exist <- file.exists("fixtures/cedar_sections_test.qs")

if (schema_fixtures_exist) {
  test_sections <<- qread("fixtures/cedar_sections_test.qs")
  test_students <<- qread("fixtures/cedar_students_test.qs")
  test_programs <<- qread("fixtures/cedar_programs_test.qs")
  test_degrees <<- qread("fixtures/cedar_degrees_test.qs")
  test_courses <<- test_sections  # alias
} else {
  # Fall back to known fixtures if schema fixtures don't exist
  message("Note: Schema fixtures not found, using known fixtures for test_* variables")
  test_sections <<- known_sections
  test_students <<- known_students
  test_programs <<- known_programs
  test_degrees <<- known_degrees
  test_courses <<- known_sections
}

# Helper function to create standard opt list
create_test_opt <- function(overrides = list()) {
  default_opt <- list(
    course_campus = NULL,
    course_college = NULL,
    dept = NULL,
    term = NULL,
    pt = NULL,
    im = NULL,
    level = NULL,
    status = "A",
    uel = TRUE,
    group_cols = NULL
  )
  
  modifyList(default_opt, overrides)
}
